// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/DeferredList dojo/dom-class dojo/dom-construct dojo/dom-style dojo/on jimu/utils esri/geometry/geometryEngine esri/geometry/Polyline esri/graphic esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query".split(" "),function(C,r,v,p,D,m,q,E,w,z,A,F,x,G,B,u,H,I,J){return C("ClosestInfo",null,{constructor:function(b,c,a){this.tab=b;
this.container=c;this.parent=a;this.graphicsLayer=this.incident=null;this.map=a.map;this.specialFields={};this.dateFields={}},updateForIncident:function(b,c,a){p.forEach(this.tab.tabLayers,r.hitch(this,function(d){if("undefined"!==typeof d.empty){var k=new G(d.url);w(k,"load",r.hitch(this,function(){this.tab.tabLayers=[k];this.processIncident(b,c,a)}))}else this.processIncident(b,c,a)}))},processIncident:function(b,c,a){this.container.innerHTML="";m.add(this.container,"loading");var d=[];this.incident=
b;c=A.buffer(b.geometry,c,this.parent.config.distanceSettings[this.parent.config.distanceUnits]);this.graphicsLayer=a;this.graphicsLayer.clear();var k=this.tab.tabLayers;a=[];for(var e=0;e<k.length;e++){var g=k[e],l=new J;l.returnGeometry=!0;l.geometry=c;l.outFields=this._getFields(g);"undefined"!==typeof g.queryFeatures&&a.push(g.queryFeatures(l))}(new D(a)).then(r.hitch(this,function(a){for(var c=0;c<a.length;c++){var h=a[c][1],e=this._getFields(k[c]);if((h=h.features)&&0<h.length){for(var f=0;f<
h.length;f++){for(var g=h[f],l={DISTANCE:this._getDistance(b.geometry,g.geometry)},m=0;m<e.length;m++)l[e[m]]=g.attributes[e[m]];g.attributes=l}h.sort(this._compareDistance);d.push(h[0])}}this._processResults(d)}))},_processResults:function(b){this.container.innerHTML="";m.remove(this.container,"loading");if(0===b.length)this.container.innerHTML=this.parent.nls.noFeaturesFound;else{var c=q.create("div",{style:"width:"+220*b.length+"px;"},this.container);m.add(c,"SAT_tabPanelContent");for(var a=this.parent.nls[this.parent.config.distanceUnits],
d=0;d<b.length;d++){var k=d+1,e=b[d],g=e.geometry,l=g;"point"!==g.type&&(l=g.getExtent().getCenter());var g=e.attributes,y;"point"===this.incident.geometry.type&&(y=a+": "+Math.round(100*g.DISTANCE)/100);var n="",h=0,s;for(s in g)if("DISTANCE"!==s&&3>h){var f=this._getFieldValue(s,g[s]),f="undefined"!==typeof f&&null!==f?z.stripHTML(f.toString()):"",t;if(e._layer&&e._layer.fields){var p=this._getField(e._layer.fields,s);p&&(t=p.alias)}if("undefined"===typeof t||t in[""," ",null,void 0])t=s;this.isURL(f)?
f='\x3ca href\x3d"'+f+'" target\x3d"_blank" style\x3d"color: inherit;"\x3e'+t+"\x3c/a\x3e":this.isEmail(f)&&(f='\x3ca href\x3d"mailto:'+f+'" style\x3d"color: inherit;"\x3e'+t+"\x3c/a\x3e");n+=f+"\x3cbr/\x3e";h+=1}e=q.create("div",{},c);m.add(e,"SATcolRec");h=q.create("div",{},e);m.add(h,"SATcolRecBar");f=q.create("div",{innerHTML:k},h);m.add(f,"SATcolRecNum");E.set(f,"backgroundColor",this.parent.config.color);w(f,"click",r.hitch(this,this._zoomToLocation,l));y&&(f=q.create("div",{innerHTML:y},h),
m.add(f,"SATcolDistance"));this.parent.config.enableRouting&&(h=q.create("div",{title:this.parent.nls.get_directions},h),m.add(h,"SATcolDir"),w(h,"click",r.hitch(this,this._routeToIncident,l)));n=q.create("div",{"class":"SATcolWrap",innerHTML:n},e);m.add(n,"SATcolInfo");n=new u(u.STYLE_SOLID,new v.fromString(this.parent.config.color),1);n=new B(B.STYLE_CIRCLE,24,n,new v.fromString(this.parent.config.color));e=new H;e.family="Arial";e.size="12px";k=new I(k,e,"#ffffff");k.setOffset(0,-4);null===g.OUTSIDE_POLYGON&&
(e=new u(u.STYLE_SOLID,new v([0,0,0,1]),1),h=new F(l.spatialReference),f=this.incident.geometry,"point"!==this.incident.geometry.type&&(f=this.incident.geometry.getExtent().getCenter()),h.addPath([l,f]),this.graphicsLayer.add(new x(h,e,{})));this.graphicsLayer.add(new x(l,n,g));this.graphicsLayer.add(new x(l,k,g))}}},_getField:function(b,c){for(var a=0;a<b.length;a++){var d=b[a];if(d.name===c||d.alias===c)return d}},_getFields:function(b){var c=[];if(this.tab.advStat&&this.tab.advStat.stats&&this.tab.advStat.stats.outFields&&
0<this.tab.advStat.stats.outFields.length)p.forEach(this.tab.advStat.stats.outFields,function(b){c.push(b.expression)});else{var a;if(b.infoTemplate)a=b.infoTemplate.info.fieldInfos;else if(0<this.parent.map.itemInfo.itemData.operationalLayers.length){var d=this.parent.map.itemInfo.itemData.operationalLayers;a=null;var k=0;a:for(;k<d.length;k++){var e=d[k];if("ArcGISMapServiceLayer"===e.layerType&&"undefined"!==typeof e.layers)for(var g=0;g<e.layers.length;g++){var l=e.layers[g];if(l.id===b.layerId&&
l.popupInfo){a=l.popupInfo.fieldInfos;break a}}}a||(a=b.fields)}else a=b.fields;if(a)for(d=0;d<a.length;d++)k=a[d],"undefined"!==typeof k.visible?k.visible&&c.push(k.fieldName):c.push(k.name)}var m={};b.fields&&p.forEach(b.fields,r.hitch(this,function(a){if("esriFieldTypeDate"===a.type||a.domain){if("esriFieldTypeDate"===a.type&&b.infoTemplate)for(var c in b.infoTemplate._fieldsMap)"undefined"!==typeof b.infoTemplate._fieldsMap[c].fieldName&&(b.infoTemplate._fieldsMap[c].fieldName===a.name&&"undefined"!==
typeof b.infoTemplate._fieldsMap[c].format.dateFormat)&&(this.dateFields[a.name]=b.infoTemplate._fieldsMap[c].format.dateFormat);m[a.name]=a}}));this.specialFields=m;return c},_getFieldValue:function(b,c){var a=c;if(this.specialFields[b]){var d=this.specialFields[b];"esriFieldTypeDate"===d.type?("undefined"!==this.dateFields[b]?(d=this.dateFields[b],d=void 0!==typeof d?{dateFormat:d}:{dateFormat:"longMonthDayYear"}):d={dateFormat:"longMonthDayYear"},a=z.fieldFormatter.getFormattedDate(new Date(c),
d)):p.some(d.domain.codedValues,function(b){if(b.code===c)return a=b.name,!0})}return a},isURL:function(b){return/(https?:\/\/|ftp:)/g.test(b)},isEmail:function(b){return/\S+@\S+\.\S+/.test(b)},_getDistance:function(b,c){var a=0,d=this.parent.config.distanceUnits,a=A.distance(b,c,9001);switch(d){case "miles":a*=6.21371E-4;break;case "kilometers":a*=0.0010;break;case "feet":a*=3.28084;break;case "yards":a*=1.09361;break;case "nauticalMiles":a*=5.39957E-4}return a},_compareDistance:function(b,c){return b.attributes.DISTANCE<
c.attributes.DISTANCE?-1:b.attributes.DISTANCE>c.attributes.DISTANCE?1:0},_zoomToLocation:function(b){this.parent.zoomToLocation(b)},_routeToIncident:function(b){this.parent.routeToIncident(b)}})});