// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Evented dojo/_base/array dojo/_base/lang dojo/_base/Color dojo/dom dojo/dom-class dojo/dom-construct dojo/dom-style dojo/number dojo/on dojo/has dijit/form/Button jimu/dijit/Popup jimu/CSVUtils jimu/utils esri/config esri/geometry/geometryEngine esri/geometry/mathUtils esri/geometry/Point esri/geometry/webMercatorUtils esri/graphic esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query".split(" "),
function(v,w,n,g,y,z,m,h,A,x,r,B,C,D,s,q,E,F,G,H,I,J,t,K,L,M,N,u){return v("GroupedCountInfo",[w],{summaryLayer:null,summaryFields:[],summaryIds:[],summaryFeatures:[],summaryGeom:null,tabNum:null,popupFields:[],groupedResults:{},symbolField:null,graphicsLayer:null,lyrRenderer:null,lyrSymbol:null,constructor:function(a,c,b){this.tab=a;this.container=c;this.parent=b;this.config=b.config;this.graphicsLayer=null;this.specialFields={};this.dateFields={}},updateForIncident:function(a,c,b,d){this.tabNum=
d;this.container.innerHTML="";m.add(this.container,"loading");this.summaryIds=[];this.summaryFeatures=[];this.groupedResults={};this.summaryGeom=c.geometry;if(0<this.tab.tabLayers.length){var e;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],e=new t(this.summaryLayer.url),e.infoTemplate=this.tab.tabLayers[0].infoTemplate,this.tab.tabLayers[1]=e,this._initGraphicsLayer(b),this.summaryFields=this._getFields(this.tab.tabLayers[0]),g.hitch(this,this._queryFeatures(c.geometry))):
(e=new t(this.tab.tabLayers[0].url),r(e,"load",g.hitch(this,function(){this.summaryLayer=e;if(-1<this.tab.tabLayers[0].url.indexOf("MapServer"))for(var a=this.tab.tabLayers[0].url.split("MapServer/")[1],d=this.parent.map.itemInfo.itemData.operationalLayers,l=0;l<d.length;l++){var k=d[l];if("undefined"!==typeof k.layerObject&&k.layerObject.infoTemplates&&(k=k.layerObject.infoTemplates[a])){e.infoTemplate=k.infoTemplate;break}}this.tab.tabLayers[1]=e;this._initGraphicsLayer(b);this.summaryFields=this._getFields(this.tab.tabLayers[1]);
g.hitch(this,this._queryFeatures(c.geometry))})))}},_initGraphicsLayer:function(a){null!==a&&(this.graphicsLayer=a,this.graphicsLayer.clear(),this.summaryLayer&&this.summaryLayer.renderer&&(this.lyrRenderer=this.summaryLayer.renderer,this.graphicsLayer.renderer=this.lyrRenderer,"undefined"!==typeof this.summaryLayer.renderer.attributeField?this.symbolField=this.summaryLayer.renderer.attributeField:this.lyrSymbol=this.lyrRenderer.symbol))},_queryFeatures:function(a){var c=new u;c.geometry=a;this.summaryLayer.queryIds(c,
g.hitch(this,function(a){a?(this.summaryIds=a,0<this.summaryIds.length?this._queryFeaturesByIds():this._processResults()):this._processResults()}))},_queryFeaturesByIds:function(){var a=this.summaryLayer.maxRecordCount||1E3,c=this.summaryIds.slice(0,a);this.summaryIds.splice(0,a);var a=new u,b=!1;n.some(this.summaryFields,g.hitch(this,function(a){if("area"===a.type||"length"===a.type||this.graphicsLayer)return b=!0}));a.returnGeometry=b;var d=[];n.forEach(this.summaryFields,function(a){d.push(a.field)});
this.symbolField&&d.push(this.symbolField);if(!0===this.config.csvAllFields||"true"===this.config.csvAllFields)a.outFields=["*"];else{if(0<this.popupFields.length)for(var e=0;e<this.popupFields.length;e++){var f=this.popupFields[e];-1===d.indexOf(f)&&d.push(f)}a.outFields=d}a.objectIds=c;this.summaryLayer.queryFeatures(a,g.hitch(this,function(a){a.features&&(this.summaryFeatures=this.summaryFeatures.concat(a.features));this._processResults();0<this.summaryIds.length?(this.SA_SAT_download&&m.replace(this.SA_SAT_download,
"processing","download"),this._queryFeaturesByIds()):this.SA_SAT_download&&m.replace(this.SA_SAT_download,"download","processing")}))},_prepGroupedResults:function(){for(var a=0;a<this.summaryFeatures.length;a++){var c=this.summaryFeatures[a];if("undefined"!==typeof this.summaryFields&&0<this.summaryFields.length){var b=this._getFieldValue(this.summaryFields[0].field,c.attributes[this.summaryFields[0].field]),b="undefined"!==typeof b&&null!==b?q.stripHTML(b.toString()):"";b in this.groupedResults?
this.groupedResults[b].features.push(c):this.groupedResults[b]={features:[c]}}}},_prepResults:function(){for(var a in this.groupedResults){var c=this.summaryFields[0];c.total=this.groupedResults[a].features.length;this.groupedResults[a].total=c.total;this.groupedResults[a].type=c.type;this.groupedResults[a].label=c.alias}},_processResults:function(){this._prepGroupedResults();this._prepResults();this.container.innerHTML="";m.remove(this.container,"loading");var a=this.groupedResults;if(0===Object.keys(this.groupedResults).length)this.container.innerHTML=
this.parent.nls.noFeaturesFound;else{var c=Object.keys(this.groupedResults).length+1,b=0,c=h.create("div",{style:"width:"+220*c+"px;"},this.container);m.add(c,"SAT_tabPanelContent");b=h.create("div",{},c);m.add(b,"SATcol");b=h.create("div",{"data-dojo-attach-point":"SA_SAT_download",innerHTML:this.parent.nls.downloadCSV},b);m.add(b,["btnExport","download"]);r(b,"click",g.hitch(this,this._exportToCSV));var d=Object.keys(a).sort(),e;for(e in d){var b=d[e],f=a[b],p=q.stripHTML(b.toString()),b=b===this.parent.nls.area||
b===this.parent.nls.length?f.total:Math.round(f.total);isNaN(b)&&(b=0);var l=h.create("div",{"class":"SATcol"},c),k=h.create("div",{style:"max-height: 45px;"},l);h.create("div",{"class":"SATcolWrap",style:"max-height: 30px; overflow: hidden;",innerHTML:"pre"===f.type?f.label.trim():p},k);h.create("div",{"class":"SATcolWrap",style:"max-height: 30px; overflow: hidden;",innerHTML:"pre"===f.type?p:f.label.trim()},k);h.create("div",{"class":""!==f.label?"colGroupedSummary":"colSummary",innerHTML:x.format(b)},
l)}if(null!==this.graphicsLayer){this.graphicsLayer.clear();this.tab.tabLayers[1].clear();if(this.summaryFeatures)for(a=0;a<this.summaryFeatures.length;a++)e=this.summaryFeatures[a],this.lyrSymbol?e.symbol=this.lyrSymbol:this.graphicsLayer.renderer&&(c=this.graphicsLayer.renderer.getSymbol(e),e.symbol=c),this.graphicsLayer.add(e),this.tab.tabLayers[1].add(e);this.graphicsLayer.setVisibility(!0);this.parent._toggleTabLayersNew(this.tabNum);this.tab.retsore&&this.emit("summary-complete",{bubbles:!0,
cancelable:!0,tab:this.tabNum})}}},_exportToCSV:function(){if(0===this.summaryFeatures.length)return!1;var a;a=this.tab.label?this.tab.label:this.tab.layers;var c=[],b=[];n.forEach(this.summaryFeatures,function(a){c.push(a.attributes)});if(!0===this.config.csvAllFields||"true"===this.config.csvAllFields)for(var d in c[0])b.push(d);else for(d=0;d<this.summaryFields.length;d++)b.push(this.summaryFields[d].field);d=this.summaryLayer.fields;if(this.summaryLayer&&this.summaryLayer.loaded&&d){var e={};
if(this.parent.opLayers&&this.parent.opLayers._layerInfos){var f=this.parent.opLayers.getLayerInfoById(this.summaryLayer.id);f&&(e.popupInfo=f.getPopupInfo())}var f=[],p=0;for(;p<b.length;p++){var l=b[p],k=!1,g,h=0;b:for(;h<d.length;h++)if(g=d[h],g.name===l){k=!0;break b}k?f.push(g):f.push({name:l,alias:l,show:!0,type:"esriFieldTypeString"})}e.datas=c;e.fromClient=!1;e.withGeometry=!1;e.outFields=f;e.formatDate=!0;e.formatCodedValue=!0;e.formatNumber=!1;s.exportCSVFromFeatureLayer(a,this.summaryLayer,
e)}else s.exportCSV(a,c,b)},_getFields:function(a){var c=[];if("undefined"!==typeof this.tab.advStat){var b=this.tab.advStat.stats,d;for(d in b)0<b[d].length&&n.forEach(b[d],function(a){c.push({field:a.expression,alias:a.label+"",type:d,total:0})})}var e={};n.forEach(a.fields,g.hitch(this,function(b){if("esriFieldTypeDate"===b.type||b.domain){if("esriFieldTypeDate"===b.type&&a.infoTemplate)for(var c in a.infoTemplate._fieldsMap)"undefined"!==typeof a.infoTemplate._fieldsMap[c].fieldName&&(a.infoTemplate._fieldsMap[c].fieldName===
b.name&&"undefined"!==typeof a.infoTemplate._fieldsMap[c].format.dateFormat)&&(this.dateFields[b.name]=a.infoTemplate._fieldsMap[c].format.dateFormat);e[b.name]=b}}));this.specialFields=e;return c},_getFieldValue:function(a,c){var b=c;if(this.specialFields[a]){var d=this.specialFields[a];"esriFieldTypeDate"===d.type?("undefined"!==this.dateFields[a]?(d=this.dateFields[a],d=void 0!==typeof d?{dateFormat:d}:{dateFormat:"longMonthDayYear"}):d={dateFormat:"longMonthDayYear"},b=q.fieldFormatter.getFormattedDate(new Date(c),
d)):n.some(d.domain.codedValues,function(a){if(a.code===c)return b=a.name,!0})}return b}})});