// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/DeferredList dojo/dom-class dojo/dom-construct dojo/dom-style dojo/on esri/geometry/geometryEngine esri/graphic esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query jimu/CSVUtils jimu/utils".split(" "),function(H,r,B,t,I,s,u,C,z,J,D,K,E,F,L,M,N,y,G){return H("ProximityInfo",null,{constructor:function(a,d,b){this.tab=a;this.container=
d;this.parent=b;this.graphicsLayer=this.incident=null;this.specialFields={};this.dateFields={};this.config=b.config},updateForIncident:function(a,d,b){t.forEach(this.tab.tabLayers,r.hitch(this,function(c){if("undefined"!==typeof c.empty){var e=new K(c.url);z(e,"load",r.hitch(this,function(){this.tab.tabLayers=[e];this.processIncident(a,d,b)}))}else this.processIncident(a,d,b)}))},processIncident:function(a,d,b){this.container.innerHTML="";this.buffer=d;s.add(this.container,"loading");var c=[];this.incident=
a;this.graphicsLayer=b;var e=this.tab.tabLayers;b=[];for(var f=0;f<e.length;f++){var k=e[f],g=new N;g.returnGeometry=!0;g.geometry=d.geometry;g.outFields="true"===this.parent.config.csvAllFields||!0===this.parent.config.csvAllFields?["*"]:this._getFields(k);"undefined"!==typeof k.queryFeatures&&b.push(k.queryFeatures(g))}(new I(b)).then(r.hitch(this,function(b){for(var d=0;d<b.length;d++){var m=b[d][1],f=this._getFields(e[d]);if(m&&m.features)for(var m=m.features,g=0;g<m.length;g++){for(var l=m[g],
k=this._getDistance(a.geometry,l.geometry),q={DISTANCE:k},n=0;n<f.length;n++)q[f[n]]=l.attributes[f[n]];!0===this.config.csvAllFields||"true"===this.config.csvAllFields?l.attributes.DISTANCE=k:l.attributes=q;c.push(l)}}this._processResults(c)}))},_processResults:function(a){this.container.innerHTML="";s.remove(this.container,"loading");this.graphicsLayer.clear();if(0===a.length&&this.buffer)this.container.innerHTML=this.parent.nls.noFeaturesFound;else{0===a.length&&!this.buffer&&(this.container.innerHTML=
this.parent.nls.defaultTabMsg);a.sort(this._compareDistance);var d=a.length+1,b=u.create("div",{style:"width:"+(220*d+20)+"px;"},this.container);s.add(b,"SAT_tabPanelContent");var c=u.create("div",{},b);s.add(c,"SATcol");c=u.create("div",{innerHTML:this.parent.nls.downloadCSV},c);s.add(c,"btnExport");z(c,"click",r.hitch(this,this._exportToCSV,a));var c=this.parent.nls[this.parent.config.distanceUnits],e;"undefined"!==typeof this.tab.advStat?e=this.tab.advStat.stats.outFields:(e=[],0<this.tab.tabLayers.length&&
t.forEach(this.tab.tabLayers,r.hitch(this,function(a){"undefined"!==typeof a.popupInfo?t.forEach(a.popupInfo.fieldInfos,r.hitch(this,function(a){if(a.visible){var b={value:0};b.expression=a.fieldName;b.label=a.label;e.push(b)}})):a.infoTemplate?t.forEach(a.infoTemplate.info.fieldInfos,r.hitch(this,function(a){if(a.visible){var b={value:0};b.expression=a.fieldName;b.label=a.label;e.push(b)}})):t.forEach((a.layerObject?a.layerObject:a).fields,r.hitch(this,function(a){var b={value:0};b.expression=a.name;
b.label=a.alias;e.push(b)}))})));for(var f=0,k=0;k<a.length;k++){var g=k+1,h=a[k],p=h.geometry,m=p;"point"!==p.type&&(m=p.getExtent().getCenter());var p=h.attributes,A;"point"===this.incident.geometry.type&&(A=c+": "+Math.round(100*p.DISTANCE)/100);var v="",l=0,w;for(w in p)if("DISTANCE"!==w&&3>l&&"undefined"!==typeof e)for(var q=0;q<e.length;q++)if(e[q].expression===w){var n=this._getFieldValue(w,p[w]),n="undefined"!==typeof n&&null!==n?G.stripHTML(n.toString()):"",x;if(h._layer&&h._layer.fields){var y=
this._getField(h._layer.fields,w);y&&(x=y.alias)}if("undefined"===typeof x||x in[""," ",null,void 0])x=w;this.isURL(n)?n='\x3ca href\x3d"'+n+'" target\x3d"_blank" style\x3d"color: inherit;"\x3e'+x+"\x3c/a\x3e":this.isEmail(n)&&(n='\x3ca href\x3d"mailto:'+n+'" style\x3d"color: inherit;"\x3e'+x+"\x3c/a\x3e");v+=n+"\x3cbr/\x3e";l+=1}h=u.create("div",{},b);s.add(h,"SATcolRec");l=u.create("div",{},h);s.add(l,"SATcolRecBar");q=u.create("div",{innerHTML:g},l);s.add(q,"SATcolRecNum");C.set(q,"backgroundColor",
this.parent.config.color);z(q,"click",r.hitch(this,this._zoomToLocation,m));A&&(q=u.create("div",{innerHTML:A},l),s.add(q,"SATcolDistance"));this.parent.config.enableRouting&&(l=u.create("div",{title:this.parent.nls.get_directions},l),s.add(l,"SATcolDir"),z(l,"click",r.hitch(this,this._routeToIncident,m)));v=u.create("div",{"class":"SATcolWrap",innerHTML:v},h);s.add(v,"SATcolInfo");f+=h.clientWidth;v=new F(F.STYLE_SOLID,new B.fromString(this.parent.config.color),1);v=new E(E.STYLE_CIRCLE,24,v,new B.fromString(this.parent.config.color));
h=new L;h.family="Arial";h.size="12px";g=new M(g,h,"#ffffff");g.setOffset(0,-4);this.graphicsLayer.add(new D(m,v,p));this.graphicsLayer.add(new D(m,g,p))}C.set(b,"width",f+240+d+"px")}},_exportToCSV:function(a){if(0===a.length)return!1;var d;d=this.tab.label?this.tab.label:this.tab.layers;var b=[],c=[];t.forEach(a,function(a){b.push(a.attributes)});for(var e in b[0])c.push(e);this.summaryLayer=this.tab.tabLayers[0];a=this.summaryLayer.fields;if(this.summaryLayer&&this.summaryLayer.loaded&&a){e={};
if(this.parent.opLayers&&this.parent.opLayers._layerInfos){var f=this.parent.opLayers.getLayerInfoById(this.summaryLayer.id);f&&(e.popupInfo=f.getPopupInfo())}var f=[],k=0;for(;k<c.length;k++){var g=c[k],h=!1,p,m=0;b:for(;m<a.length;m++)if(p=a[m],p.name===g){h=!0;break b}h?f.push(p):f.push({name:g,alias:g,show:!0,type:"esriFieldTypeString"})}e.datas=b;e.fromClient=!1;e.withGeometry=!1;e.outFields=f;e.formatDate=!0;e.formatCodedValue=!0;e.formatNumber=!1;y.exportCSVFromFeatureLayer(d,this.summaryLayer,
e)}else y.exportCSV(d,b,c)},_getField:function(a,d){for(var b=0;b<a.length;b++){var c=a[b];if(c.name===d||c.alias===d)return c}},_getFields:function(a){var d=[];if(this.tab.advStat&&this.tab.advStat.stats&&this.tab.advStat.stats.outFields&&0<this.tab.advStat.stats.outFields.length)t.forEach(this.tab.advStat.stats.outFields,function(a){d.push(a.expression)});else{var b;if(a.infoTemplate)b=a.infoTemplate.info.fieldInfos;else if(0<this.parent.map.itemInfo.itemData.operationalLayers.length){var c=this.parent.map.itemInfo.itemData.operationalLayers;
b=null;var e=0;a:for(;e<c.length;e++){var f=c[e];if("ArcGISMapServiceLayer"===f.layerType&&"undefined"!==typeof f.layers)for(var k=0;k<f.layers.length;k++){var g=f.layers[k];if(g.popupInfo&&g.id===a.layerId){b=g.popupInfo.fieldInfos;break a}}}b||(b=a.fields)}else b=a.fields;for(c=0;c<b.length;c++)e=b[c],"undefined"!==typeof e.visible?e.visible&&d.push(e.fieldName):d.push(e.name)}var h={};t.forEach(a.fields,r.hitch(this,function(b){if("esriFieldTypeDate"===b.type||b.domain){if("esriFieldTypeDate"===
b.type&&a.infoTemplate)for(var c in a.infoTemplate._fieldsMap)"undefined"!==typeof a.infoTemplate._fieldsMap[c].fieldName&&(a.infoTemplate._fieldsMap[c].fieldName===b.name&&"undefined"!==typeof a.infoTemplate._fieldsMap[c].format.dateFormat)&&(this.dateFields[b.name]=a.infoTemplate._fieldsMap[c].format.dateFormat);h[b.name]=b}}));this.specialFields=h;return d},_getFieldValue:function(a,d){var b=d;if(this.specialFields[a]){var c=this.specialFields[a];"esriFieldTypeDate"===c.type?("undefined"!==this.dateFields[a]?
(c=this.dateFields[a],c=void 0!==typeof c?{dateFormat:c}:{dateFormat:"longMonthDayYear"}):c={dateFormat:"longMonthDayYear"},b=G.fieldFormatter.getFormattedDate(new Date(d),c)):t.some(c.domain.codedValues,function(a){if(a.code===d)return b=a.name,!0})}return b},isURL:function(a){return/(https?:\/\/|ftp:)/g.test(a)},isEmail:function(a){return/\S+@\S+\.\S+/.test(a)},_getDistance:function(a,d){var b=0,c=this.parent.config.distanceUnits,b=J.distance(a,d,9001);switch(c){case "miles":b*=6.21371E-4;break;
case "kilometers":b*=0.0010;break;case "feet":b*=3.28084;break;case "yards":b*=1.09361;break;case "nauticalMiles":b*=5.39957E-4}return b},_compareDistance:function(a,d){return a.attributes.DISTANCE<d.attributes.DISTANCE?-1:a.attributes.DISTANCE>d.attributes.DISTANCE?1:0},_zoomToLocation:function(a){this.parent.zoomToLocation(a)},_routeToIncident:function(a){this.parent.routeToIncident(a)}})});